//bildernamen.js
var headlines = new Array();
var i = 0;
//headlines[i++]='<center><font size="-2">Thema 1: Kopfdarm, Lernspiel von Katrin Wöhrle</font></center>';
var zeige_bild_name = false;
var max_zusammenpassende_bilder = 2;
var verdecktes_bild_name = "bilder-teil-1/verdeckt.png";   
var vordefinierte_bilder_namen = new Array();
i = 0;
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_1.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_1.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_2.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_2.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_3.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_3.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_4.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_4.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_5.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_5.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_6.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_6.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_7.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_7.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_8.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_8.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_frage_9.png";
vordefinierte_bilder_namen[i++] = "bilder-teil-1/kopfdarm_antwort_9.png";
